name: Machine-Learning-Model
on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Train my model
    env:
    repo_token: ${{ secrets.GITHUB_TOKEN }}
    run: |
     pip install -r requirments.txt
     python machine_learning.py
     
     echo " ## Model Metrics" > reprt.md
     cat metrics.txt >> report.md
     
     cml-send-cimment report.md
